# Generated by Django 4.1.5 on 2023-01-11 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='grade',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Grade'),
        ),
        migrations.AlterField(
            model_name='user',
            name='salary',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='Salary'),
        ),
        migrations.AlterField(
            model_name='user',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Title'),
        ),
    ]
